server:
    port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marry?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root